2020-06-21 00:11:02.8096|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:11:03.9262|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:11:04.0241|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:11:04.6470|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:11:16.5501|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:11:16.6733|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:12:54.8854|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 00:12:55.4002|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"Value cannot be null. (Parameter 's')\r\n                                         \r\n\r\n                                            at System.Int32.Parse(String s)\r\n   at WedigITCRM.Controllers.PurchaseOrderController.saveOrderLine(PurchaseOrderLineModel model, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 397\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"224bcfa4-8d4b-4de4-9f29-ffb32b8296fd","Extensions":{}}
2020-06-21 00:22:50.5207|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:22:51.8009|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:22:51.9473|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:22:53.8830|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:23:00.3666|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:23:00.4122|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:26:45.0783|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:26:46.2031|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:26:46.3132|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:26:46.8872|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:26:50.8901|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:26:51.1849|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:37:47.5521|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:37:48.6509|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:37:48.8163|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:37:49.4056|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:37:55.8101|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:37:55.8967|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
2020-06-21 00:41:27.0653|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
2020-06-21 00:41:27.2969|ERROR|WedigITCRM.Startup|{"UserId":"6c1e27cf-820e-4335-b9a5-7ed1142c531c","UserName":"johnpetersen1959@gmail.com","CompanyId":"13024","CompanyName":"wedigIT ApS","Type":null,"Title":"Unexpected Error","Status":500,"Detail":"Could not find file 'C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\wwwroot\\CustomerAttachments\\514ccc67-e9c1-44e4-b835-83e967753696_purchaseOrder.pdf'.\r\n                                         \r\n\r\n                                            at System.IO.FileInfo.get_Length()\r\n   at WedigITCRM.Controllers.PurchaseOrderController.sendPurchaseOrder(Int32 purchaseOrderId, CompanyAccount companyAccount) in C:\\Users\\John\\source\\repos\\WedigITCRM\\WedigITCRM\\Controllers\\PurchaseOrderController.cs:line 633\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","Instance":"944fa928-e92a-4431-9699-f1eee7582df9","Extensions":{}}
2020-06-21 00:43:50.3971|ERROR|WedigITCRM.Startup|start of ConfigureServices
2020-06-21 00:43:51.4138|ERROR|WedigITCRM.Startup|end of ConfigureServices
2020-06-21 00:43:51.4940|ERROR|WedigITCRM.Startup|start of Configure method
2020-06-21 00:43:52.0791|ERROR|WedigITCRM.Startup|end of Configure method
2020-06-21 00:43:56.6122|ERROR|WedigITCRM.Controllers.HomeController|Entering index action in home controller
2020-06-21 00:43:56.6606|ERROR|WedigITCRM.Controllers.HomeController|index action in home controller redirecting to Customer controller AllCustomers action
